import { CourseDocument, DocumentChunk } from '../types';

export function chunkText(rawText: string, docId: string, docTitle: string, subject: string): DocumentChunk[] {
  // Split into logical sections or paragraphs (~300-600 characters)
  const paragraphs = rawText
    .split(/\n\s*\n/)
    .map(p => p.trim())
    .filter(p => p.length > 20);

  const chunks: DocumentChunk[] = [];
  let currentAccumulator = '';
  let chunkIdx = 1;

  for (const para of paragraphs) {
    if (currentAccumulator.length + para.length > 700 && currentAccumulator.length > 0) {
      const words = currentAccumulator.toLowerCase().match(/\b[a-z]{3,}\b/g) || [];
      const freq: Record<string, number> = {};
      words.forEach(w => { freq[w] = (freq[w] || 0) + 1; });
      const topKeywords = Object.entries(freq)
        .sort((a, b) => b[1] - a[1])
        .slice(0, 5)
        .map(e => e[0]);

      chunks.push({
        id: `${docId}_chunk_${chunkIdx}`,
        documentId: docId,
        documentTitle: docTitle,
        subject,
        chunkIndex: chunkIdx,
        content: currentAccumulator.trim(),
        keywords: topKeywords
      });
      chunkIdx++;
      currentAccumulator = para;
    } else {
      currentAccumulator = currentAccumulator ? `${currentAccumulator}\n\n${para}` : para;
    }
  }

  if (currentAccumulator.trim().length > 0) {
    const words = currentAccumulator.toLowerCase().match(/\b[a-z]{3,}\b/g) || [];
    const freq: Record<string, number> = {};
    words.forEach(w => { freq[w] = (freq[w] || 0) + 1; });
    const topKeywords = Object.entries(freq)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 5)
      .map(e => e[0]);

    chunks.push({
      id: `${docId}_chunk_${chunkIdx}`,
      documentId: docId,
      documentTitle: docTitle,
      subject,
      chunkIndex: chunkIdx,
      content: currentAccumulator.trim(),
      keywords: topKeywords
    });
  }

  return chunks;
}

const OS_TEXT = `Unit 1: Process Concurrency and Deadlocks
Operating Systems manage multiple processes executing concurrently. When processes share resources, synchronization mechanisms such as Mutexes and Semaphores are required to prevent race conditions. A race condition occurs when multiple execution threads manipulate shared state simultaneously and the final output depends on execution order.

A Deadlock is an exceptional state where two or more processes are unable to proceed because each is waiting for a resource acquired by the other. Coffman's Four Conditions must hold simultaneously for a deadlock to occur:
1. Mutual Exclusion: At least one resource must be held in a non-shareable mode.
2. Hold and Wait: A process holding at least one resource must be waiting to acquire additional resources held by other processes.
3. No Preemption: Resources cannot be forcibly preempted; they are released only voluntarily by the holding process.
4. Circular Wait: A closed chain of processes exists such that each process holds a resource needed by the next process in the cycle.

Deadlock Prevention and Avoidance:
Deadlock prevention works by invalidating at least one of the four Coffman conditions (e.g., imposing total resource ordering to eliminate circular wait).
Deadlock avoidance dynamically examines resource allocation state. Dijkstra's Banker's Algorithm ensures the system never enters an unsafe state. A state is defined as safe if there exists a safe sequence of processes <P1, P2, ... Pn> such that each process can satisfy its maximum remaining resource need with the currently available resources plus resources freed by previously finished processes.

Unit 2: Virtual Memory & Page Replacement
Virtual Memory decouples the user logical memory address space from the physical RAM address space, allowing processes to execute without being fully resident in physical memory.
Paging divides logical memory into fixed-sized blocks called pages, and physical memory into corresponding frames. The Memory Management Unit (MMU) utilizes a Page Table and a Translation Lookaside Buffer (TLB) hardware cache to map virtual page numbers (VPN) to physical frame numbers (PFN).

When a referenced page is not present in physical RAM, a Page Fault trap is generated by CPU hardware. The Operating System suspends the process, locates the missing page in secondary swap storage, reads it into an available physical frame, updates the page table valid/invalid bit, and restarts the instruction.
Page Replacement Algorithms:
1. FIFO (First-In, First-Out): Replaces the oldest page loaded into memory. Suffers from Belady's Anomaly (increasing frame allocation can counterintuitively increase page faults).
2. LRU (Least Recently Used): Replaces the page that has not been accessed for the longest time interval. Implemented via access timestamps or stack structures; LRU satisfies the stack property and avoids Belady's Anomaly.
3. Optimal (OPT / MIN): Replaces the page that will not be used for the longest future time interval. Serves as theoretical upper bound benchmark.`;

const ML_TEXT = `Module 1: Supervised Learning Fundamentals and Bias-Variance Tradeoff
Supervised machine learning algorithms learn a mapping function f: X -> y from labeled training pairs. Models can be parametric (e.g., Linear Regression, Logistic Regression) where hypotheses are constrained to fixed functional forms, or non-parametric (e.g., k-Nearest Neighbors, Decision Trees) where model capacity scales with training data size.

The Bias-Variance Decomposition defines total expected generalization error into three distinct components:
1. Bias Error: Error introduced by erroneous or overly simplistic assumptions in the learning algorithm. High bias leads to underfitting where the model fails to capture underlying patterns in training data.
2. Variance Error: Sensitivity to small fluctuations and noise in the training set. High variance leads to overfitting where the model memorizes idiosyncratic training noise rather than true population distribution.
3. Irreducible Noise: Inherent noise in the problem domain epsilon that cannot be reduced regardless of model choice.

Techniques to Mitigate Overfitting:
- Regularization: Adds a penalization term lambda * Omega(w) to the objective loss function.
  - L2 Regularization (Ridge): Penalizes squared Euclidean norm ||w||_2^2, shrinking weights smoothly towards zero without driving them completely to zero.
  - L1 Regularization (Lasso): Penalizes absolute norm ||w||_1, driving non-essential feature weights strictly to zero, effectively performing automatic sparse feature selection.
  - ElasticNet: Combines both L1 and L2 penalties with a mixing ratio parameter.
- Cross-Validation: K-fold cross-validation divides data into K equal partitions, training on K-1 folds and validating on the remaining fold across K iterations to verify stability.
- Early Stopping: Halts iterative optimization once validation loss starts increasing even while training loss continues falling.

Module 2: Model Evaluation Metrics
For classification problems with class imbalance, standard Classification Accuracy is misleading.
Key Metrics:
- Precision = TP / (TP + FP): Proportion of predicted positive instances that were truly positive. Essential when False Positives are expensive (e.g., spam email filtering).
- Recall (Sensitivity) = TP / (TP + FN): Proportion of actual positives successfully identified. Essential when False Negatives are dangerous (e.g., disease diagnosis).
- F1-Score = 2 * (Precision * Recall) / (Precision + Recall): The harmonic mean of precision and recall.
- ROC-AUC: Area Under the Receiver Operating Characteristic curve plotting True Positive Rate vs False Positive Rate across all classification thresholds. An AUC of 1.0 indicates perfect discrimination.`;

const DSA_TEXT = `Section 1: Binary Search Trees and Self-Balancing AVL Trees
A Binary Search Tree (BST) is an ordered node-based tree data structure where for every node X, all keys in the left subtree are strictly less than X.key, and all keys in the right subtree are strictly greater than X.key.
In a balanced BST, search, insertion, and deletion exhibit O(log N) time complexity. However, if keys are inserted in sequential or sorted order, the BST degrades into a linear linked list with degenerate O(N) operations.

AVL Trees (Adelson-Velsky and Landis):
An AVL tree is a self-balancing binary search tree. For every node, the Balance Factor BF(node) = height(left_subtree) - height(right_subtree) must be strictly within {-1, 0, +1}.
When an insertion or deletion violates this property (|BF| > 1), balance is restored using tree rotations:
1. Left-Left (LL) Heavy: Fixed with a Single Right Rotation.
2. Right-Right (RR) Heavy: Fixed with a Single Left Rotation.
3. Left-Right (LR) Heavy: Fixed with a Left Rotation on the left child, followed by a Right Rotation on the parent node.
4. Right-Left (RL) Heavy: Fixed with a Right Rotation on the right child, followed by a Left Rotation on the parent node.
Because tree height is strictly maintained at h <= 1.44 * log2(N), worst-case search, insertion, and deletion are guaranteed O(log N).

Section 2: Graph Algorithms and Dijkstra's Shortest Path
Graphs G = (V, E) represent relationships between vertices V and edges E.
Traversal Algorithms:
- Breadth-First Search (BFS): Explores vertices level-by-level using a FIFO Queue. BFS finds the shortest path in unweighted graphs with O(V + E) complexity.
- Depth-First Search (DFS): Explores deeply along each branch using recursion or a LIFO Stack. Useful for topological sorting, detecting cycles, and connected components.

Dijkstra's Algorithm:
Finds the single-source shortest path to all vertices in a weighted graph with non-negative edge weights.
Algorithm Steps:
1. Initialize distances dist[source] = 0, and dist[v] = infinity for all other vertices v in V.
2. Maintain a Min-Priority Queue of unvisited vertices keyed on their tentative distance dist[u].
3. Extract the minimum distance vertex u from the priority queue.
4. For each neighbor v of u with edge weight w(u, v):
   Relaxation step: If dist[u] + w(u, v) < dist[v], update dist[v] = dist[u] + w(u, v) and update the priority queue.
5. Repeat until all vertices have been processed.
Time Complexity: O((V + E) * log V) using a binary heap priority queue. Note: Dijkstra fails on graphs with negative edge weights; in such cases, the Bellman-Ford algorithm O(V * E) must be used.`;

export const DEFAULT_MATERIALS: CourseDocument[] = [
  {
    id: 'doc_os_01',
    title: 'Operating Systems: Concurrency, Deadlocks & Virtual Memory',
    subject: 'Operating Systems',
    fileName: 'CS301_OS_Unit1_Unit2_Notes.pdf',
    fileSize: 48200,
    uploadedAt: '2026-09-08T10:30:00Z',
    rawText: OS_TEXT,
    chunks: chunkText(OS_TEXT, 'doc_os_01', 'Operating Systems: Concurrency, Deadlocks & Virtual Memory', 'Operating Systems'),
    tags: ['Concurrency', 'Deadlocks', 'Virtual Memory', 'Paging', 'Banker Algorithm'],
    isDefault: true
  },
  {
    id: 'doc_ml_02',
    title: 'Machine Learning: Supervised Models, Regularization & Evaluation',
    subject: 'Machine Learning',
    fileName: 'ML402_Supervised_Learning_Syllabus.md',
    fileSize: 53100,
    uploadedAt: '2026-09-09T14:15:00Z',
    rawText: ML_TEXT,
    chunks: chunkText(ML_TEXT, 'doc_ml_02', 'Machine Learning: Supervised Models, Regularization & Evaluation', 'Machine Learning'),
    tags: ['Bias-Variance', 'Regularization', 'L1/L2', 'Precision-Recall', 'ROC-AUC'],
    isDefault: true
  },
  {
    id: 'doc_dsa_03',
    title: 'Data Structures & Algorithms: Trees, Graphs & Shortest Paths',
    subject: 'Data Structures & Algorithms',
    fileName: 'CS204_DSA_Advanced_Trees_Graphs.txt',
    fileSize: 61400,
    uploadedAt: '2026-09-10T09:00:00Z',
    rawText: DSA_TEXT,
    chunks: chunkText(DSA_TEXT, 'doc_dsa_03', 'Data Structures & Algorithms: Trees, Graphs & Shortest Paths', 'Data Structures & Algorithms'),
    tags: ['AVL Trees', 'Rotations', 'Dijkstra', 'BFS/DFS', 'Graph Algorithms'],
    isDefault: true
  }
];

export const INITIAL_STUDENT_PROFILE = {
  id: 'std_01',
  name: 'Vignesh Pandian',
  email: 'vigneshpandian6103@gmail.com',
  degree: 'B.Tech in Computer Science & Engineering',
  semester: 'Semester 6',
  studyGoal: 'Master OS Concurrency & ML Foundations for Upcoming Midterm Exams',
  dailyTargetHours: 2.5,
  streakDays: 4,
  totalStudyMinutes: 380,
  completedQuizzesCount: 3,
  averageScore: 84
};

export const INITIAL_MEMORY = {
  completedTopics: [
    'Process Synchronization basics & Semaphores',
    'Linear Regression & Gradient Descent',
    'Binary Search Tree insertion & deletion'
  ],
  weakAreas: [
    'Dijkstra priority queue complexity nuances',
    'Coffman circular wait prevention techniques',
    'L1 vs L2 regularization geometric interpretation'
  ],
  strengths: [
    'Page replacement algorithms (FIFO, LRU)',
    'Precision and Recall trade-offs',
    'AVL tree rotations (LL & RR)'
  ],
  recentTopics: [
    'Deadlock Avoidance & Banker Algorithm',
    'Bias-Variance Decomposition',
    'Virtual Memory & Page Fault handling'
  ],
  lastActiveDate: '2026-09-10',
  keyInsights: [
    'Student learns best with real-world analogies and concrete code-level pseudocode.',
    'Student prepares for a 3-day sprint before midterm assessments.',
    'Frequently requests practice questions after reviewing theoretical concepts.'
  ],
  confidenceRatings: {
    'Operating Systems - Deadlocks': 4,
    'Operating Systems - Virtual Memory': 5,
    'Machine Learning - Bias-Variance': 4,
    'Machine Learning - Regularization': 3,
    'Data Structures - AVL Trees': 4,
    'Data Structures - Dijkstra': 3
  }
};
